import type { AuditReport } from "../types";

export const DEMO_AUDIT_REPORT: AuditReport = {
  generatedAt: "2026-09-25T00:00:00Z",
  valid: true,
  provenance: {
    databasePath: "synthetic://audit-fixture.db",
    configPath: "synthetic://audit-fixture.jsonc",
    catalogPath: "synthetic://pricing.json",
    catalogVersion: 1,
    catalogSourceVersion: "audit-fixture-1",
    catalogGeneratedAt: "2026-09-25T00:00:00Z",
    catalogRateCount: 2,
  },
  summary: {
    allSessions: 7,
    totalMessages: 10,
    sessionsWithAssistant: 6,
    assistantMessages: 9,
    ignoredMessages: 1,
    recalculableMessages: 5,
    customRateMessages: 4,
    catalogRateMessages: 2,
    storedFallbackMessages: 4,
    missingTokenMessages: 1,
    missingDateMessages: 1,
    missingRateMessages: 3,
    storedCostTotal: 513.5,
    calculatedCostTotal: 40,
    selectedCostTotal: 58.5,
    tokens: { input: 7_000_000, output: 5_000_000, cacheRead: 1_000_000, cacheWrite: 1_000_000, reasoning: 1_000_000 },
    anomalyCounts: { missingTokens: 1, missingDate: 1, missingRate: 3, invalidRate: 0, storedCostFallback: 4 },
  },
  messages: [
    {
      messageId: "m-before", sessionId: "s-history", project: "/fixture/history", provider: "fixture-history", model: "fixture-model",
      messageDate: 1_735_689_599_000, tokens: { input: 1_000_000, output: 0, cacheRead: 0, cacheWrite: 0, reasoning: 0 },
      storedCost: 4, calculatedCost: null, selectedCost: 4, costSource: "stored", rateSource: null, effectiveFrom: null, rate: null, breakdown: null,
      anomalies: ["missingRate", "storedCostFallback"],
    },
    {
      messageId: "m-child", sessionId: "s-child", project: "/fixture/parent", provider: "fixture-custom", model: "fixture-model",
      messageDate: 1_767_484_801_000, tokens: { input: 0, output: 1_000_000, cacheRead: 0, cacheWrite: 0, reasoning: 0 },
      storedCost: 99, calculatedCost: 8, selectedCost: 8, costSource: "configured", rateSource: "configured", effectiveFrom: null,
      rate: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 1.5 },
      breakdown: { input: 0, output: 8, cacheRead: 0, cacheWrite: 0, reasoning: 0, total: 8 }, anomalies: [],
    },
    {
      messageId: "m-custom", sessionId: "s-custom", project: "/fixture/custom", provider: "fixture-custom", model: "fixture-model",
      messageDate: 1_735_689_601_000, tokens: { input: 1_000_000, output: 1_000_000, cacheRead: 1_000_000, cacheWrite: 1_000_000, reasoning: 1_000_000 },
      storedCost: 99, calculatedCost: 20, selectedCost: 20, costSource: "configured", rateSource: "configured", effectiveFrom: null,
      rate: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 1.5 },
      breakdown: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 1.5, reasoning: 8, total: 20 }, anomalies: [],
    },
    {
      messageId: "m-fallback", sessionId: "s-fallback", project: "/fixture/fallback", provider: "fixture-unknown", model: "fixture-model",
      messageDate: 1_767_225_601_000, tokens: { input: 1_000_000, output: 0, cacheRead: 0, cacheWrite: 0, reasoning: 0 },
      storedCost: 4.25, calculatedCost: null, selectedCost: 4.25, costSource: "stored", rateSource: null, effectiveFrom: null, rate: null, breakdown: null,
      anomalies: ["missingRate", "storedCostFallback"],
    },
    {
      messageId: "m-new", sessionId: "s-history", project: "/fixture/history", provider: "fixture-history", model: "fixture-model",
      messageDate: 1_772_323_200_000, tokens: { input: 1_000_000, output: 1_000_000, cacheRead: 0, cacheWrite: 0, reasoning: 0 },
      storedCost: 99, calculatedCost: 7, selectedCost: 7, costSource: "catalog", rateSource: "catalog", effectiveFrom: "2026-01-01T00:00:00Z",
      rate: { input: 3, output: 4, cacheRead: 0, cacheWrite: 0 },
      breakdown: { input: 3, output: 4, cacheRead: 0, cacheWrite: 0, reasoning: 0, total: 7 }, anomalies: [],
    },
    {
      messageId: "m-no-date", sessionId: "s-invalid", project: "/fixture/invalid", provider: "fixture-history", model: "fixture-model",
      messageDate: null, tokens: { input: 1_000_000, output: 1_000_000, cacheRead: 0, cacheWrite: 0, reasoning: 0 },
      storedCost: 6.75, calculatedCost: null, selectedCost: 6.75, costSource: "stored", rateSource: null, effectiveFrom: null, rate: null, breakdown: null,
      anomalies: ["missingDate", "missingRate", "storedCostFallback"],
    },
    {
      messageId: "m-no-tokens", sessionId: "s-invalid", project: "/fixture/invalid", provider: "fixture-custom", model: "fixture-model",
      messageDate: 1_767_312_001_000, tokens: null, storedCost: 3.5, calculatedCost: null, selectedCost: 3.5, costSource: "stored", rateSource: "configured", effectiveFrom: null,
      rate: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 1.5 }, breakdown: null, anomalies: ["missingTokens", "storedCostFallback"],
    },
    {
      messageId: "m-old", sessionId: "s-history", project: "/fixture/history", provider: "fixture-history", model: "fixture-model",
      messageDate: 1_751_328_000_000, tokens: { input: 1_000_000, output: 1_000_000, cacheRead: 0, cacheWrite: 0, reasoning: 0 },
      storedCost: 99, calculatedCost: 3, selectedCost: 3, costSource: "catalog", rateSource: "catalog", effectiveFrom: "2025-01-01T00:00:00Z",
      rate: { input: 1, output: 2, cacheRead: 0, cacheWrite: 0 },
      breakdown: { input: 1, output: 2, cacheRead: 0, cacheWrite: 0, reasoning: 0, total: 3 }, anomalies: [],
    },
    {
      messageId: "m-parent", sessionId: "s-parent", project: "/fixture/parent", provider: "fixture-custom", model: "fixture-model",
      messageDate: 1_767_398_401_000, tokens: { input: 1_000_000, output: 0, cacheRead: 0, cacheWrite: 0, reasoning: 0 },
      storedCost: 99, calculatedCost: 2, selectedCost: 2, costSource: "configured", rateSource: "configured", effectiveFrom: null,
      rate: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 1.5 },
      breakdown: { input: 2, output: 0, cacheRead: 0, cacheWrite: 0, reasoning: 0, total: 2 }, anomalies: [],
    },
  ],
  ignored: [{ messageId: "u-custom", sessionId: "s-custom", role: "user", reason: "nonAssistant" }],
  sessions: [
    { sessionId: "s-child", project: "/fixture/parent", title: "Child session", parentId: "s-parent", assistantMessages: 1, cost: 8, tokens: { input: 0, output: 1_000_000, cacheRead: 0, cacheWrite: 0, reasoning: 0 }, messageIds: ["m-child"] },
    { sessionId: "s-custom", project: "/fixture/custom", title: "Custom rates", parentId: null, assistantMessages: 1, cost: 20, tokens: { input: 1_000_000, output: 1_000_000, cacheRead: 1_000_000, cacheWrite: 1_000_000, reasoning: 1_000_000 }, messageIds: ["m-custom"] },
    { sessionId: "s-empty", project: "/fixture/empty", title: "Empty session", parentId: null, assistantMessages: 0, cost: 0, tokens: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, reasoning: 0 }, messageIds: [] },
    { sessionId: "s-fallback", project: "/fixture/fallback", title: "Stored fallback", parentId: null, assistantMessages: 1, cost: 4.25, tokens: { input: 1_000_000, output: 0, cacheRead: 0, cacheWrite: 0, reasoning: 0 }, messageIds: ["m-fallback"] },
    { sessionId: "s-history", project: "/fixture/history", title: "Historical rates", parentId: null, assistantMessages: 3, cost: 14, tokens: { input: 3_000_000, output: 2_000_000, cacheRead: 0, cacheWrite: 0, reasoning: 0 }, messageIds: ["m-before", "m-new", "m-old"] },
    { sessionId: "s-invalid", project: "/fixture/invalid", title: "Invalid source data", parentId: null, assistantMessages: 2, cost: 10.25, tokens: { input: 1_000_000, output: 1_000_000, cacheRead: 0, cacheWrite: 0, reasoning: 0 }, messageIds: ["m-no-date", "m-no-tokens"] },
    { sessionId: "s-parent", project: "/fixture/parent", title: "Parent session", parentId: null, assistantMessages: 1, cost: 2, tokens: { input: 1_000_000, output: 0, cacheRead: 0, cacheWrite: 0, reasoning: 0 }, messageIds: ["m-parent"] },
  ],
  invariants: { valid: true, failed: [] },
};
